spring.application.name=Project1

#Researched how to run postgres
spring.datasource.url=jdbc:h2:~/Documents/testDb
spring.datasource.username=sa
spring.datasource.password=sa

spring.security.user.name=user
spring.security.user.password=user

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
